import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {
  Box,
  Button,
  Flex, Icon,
  Slider,
  SliderFilledTrack,
  SliderThumb,
  SliderTrack,
  Textarea,
  VStack
} from "@chakra-ui/react";
import React, { ChangeEvent, UIEvent } from "react";
import { unicode2latex, convertInterfaceFunction, convertAlgorithmFunction } from "../utils/utils";
import { AiFillGithub } from "react-icons/ai";

const Home: NextPage = () => {
  const [output, setOutput] = React.useState("");
  const [fontSize, setFontSize] = React.useState(1.15);
  const [textAreaSize, setTextareaSize] = React.useState(50);
  const [ignoreScroll, setIgnoreScroll] = React.useState(false);

  const handleInput = (e: ChangeEvent<HTMLTextAreaElement>) => {
    const input = (e.target.value).trim().replace(/\n+$/, '').split('---');
    setOutput(input.map((functionInput) =>
      functionInput && unicode2latex(/pre *≡/i.test(functionInput) ?
        convertInterfaceFunction(functionInput) :
        convertAlgorithmFunction(functionInput) )).join('\n'));
  }

  const handleScroll = (e: UIEvent<HTMLTextAreaElement>) => {
    const target = e.target as HTMLTextAreaElement;
    if (!ignoreScroll) {
      if (target.id === 'latex-textarea') {
        document.querySelector('#tad-textarea')!.scrollTo(0, target.scrollTop);
      } else {
        document.querySelector('#latex-textarea')!.scrollTo(0, target.scrollTop);
      }
    }
    setIgnoreScroll(!ignoreScroll);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>tad2latex</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <main className={styles.main}>
        <Slider aria-label='slider-ex-1' defaultValue={50} marginBottom={6} step={0.1}
                onChange={setTextareaSize}>
          <SliderTrack height={2}>
            <SliderFilledTrack/>
          </SliderTrack>
          <SliderThumb height={4} width={4}/>
        </Slider>
        <Flex width='100%' height='100vh'
              fontFamily='Consolas,Monaco,Lucida Console,Liberation Mono,
                          DejaVu Sans Mono,Bitstream Vera Sans Mono,Courier New, monospace'
              fontSize={`${fontSize}rem`} color='whiteish'>
          <VStack width={`${textAreaSize}%`}>
            <Textarea width='100%' height='100%' id='tad-textarea' colorScheme='blackAlpha'
                      resize='none'
                      backgroundColor='editor'
                      spellCheck={false}
                      fontSize='inherit'
                      color='inherit'
                      placeholder="Funciones y algoritmos"
                      onChange={handleInput}
                      onScroll={handleScroll}/>
            <Flex width='100%' fontFamily='sans-serif' justifyContent='space-evenly'>
              <Button colorScheme='blackAlpha' ml={4}
                      onClick={() => {
                        const tadTextarea: HTMLTextAreaElement = document.querySelector('#tad-textarea')!;
                        const latexTextarea: HTMLTextAreaElement = document.querySelector('#latex-textarea')!;
                        tadTextarea.value = "";
                        latexTextarea.value = "";
                      }}>
                Clear
              </Button>
              <Button colorScheme='blackAlpha' mr={4}
                      onClick={() => {
                        const textarea: HTMLTextAreaElement = document.querySelector('#tad-textarea')!;
                        textarea.select();
                        navigator.clipboard.writeText(textarea.value).then();
                      }}>
                Copy to clipboard
              </Button>
            </Flex>
          </VStack>
          <VStack width={`${100 - textAreaSize}%`}>
            <Textarea width='100%' height='100%' readOnly={true} resize='none' id='latex-textarea' colorScheme='blackAlpha'
                      backgroundColor='editor'
                      spellCheck={false}
                      fontSize='inherit'
                      color='inherit'
                      placeholder="Conversión a LaTeX"
                      onScroll={handleScroll}
                      value={output}/>
            <Flex width='100%' fontFamily='sans-serif' justifyContent='space-evenly'>
              <Button fontFamily='sans-serif' colorScheme='blackAlpha' mr={2}
                      onClick={() => {
                        const textarea: HTMLTextAreaElement = document.querySelector('#latex-textarea')!;
                        textarea.select();
                        navigator.clipboard.writeText(textarea.value).then();
                      }}>
                Copy to clipboard
              </Button>
            </Flex>
          </VStack>
        </Flex>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/f7olivera/tad2latex"
          target="_blank"
          rel="noopener noreferrer"
        >
          <Icon as={AiFillGithub} color='white' fontSize='xxx-large' />
        </a>
      </footer>
    </div>
  )
}

export default Home
